# Site settings
title: Oliver Montesino PÃ©rez
description: SysAdmin & Software Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://olivermontesino.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oliver Montesino
user_description: SysAdmin making my way in to Web & Software Development
user_title: Software Developer
email: xquendix@gmail.com
twitter_username: QuendiGeek
github_username:  olivermontesino
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
